parameters:
#    author.example.class: Custom\AuthorBundle\Example

services:
#    author.example:
#        class: %author.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
